language: node_js

node_js: 
  - 13

services:
  - docker

script:
  
  # Build
  - echo '_____________beginning build'
  - docker build -t udagram-api-feed:v6 ./udagram-api-feed
  - docker build -t udagram-api-user:v6 ./udagram-api-user
  - docker build -t udagram-frontend:v7 ./udagram-frontend
  - docker build -t reverseproxy:v6 ./udagram-reverseproxy  

  # Tagging
  - echo '_____________beginning tag'
  - docker tag udagram-api-feed:v6 emb1605272/udagram-api-feed:v6
  - docker tag udagram-api-user:v6 emb1605272/udagram-api-user:v6
  - docker tag udagram-frontend:v7 emb1605272/udagram-frontend:v7
  - docker tag reverseproxy:v6 emb1605272/reverseproxy:v6

  - echo 'DOCKER IMAGE LS____'
  - docker image ls
after_success:
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  # Login Docker  
  - echo '________LOGIN_______'
  #- docker login -u=emb1605272 -p=EP3E2Mr&&
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  #- echo 'username, password'  $DOCKER_USERNAME $DOCKER_PASSWORD
  # Pushing 
  - echo '_____________beginning push image'
  - docker push emb1605272/udagram-api-feed:v6
  - docker push emb1605272/udagram-api-user:v6
  - docker push emb1605272/udagram-frontend:v7
  - docker push emb1605272/reverseproxy:v6