language: node_js
node_js: 13
services:
  - docker

script:
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy  

  # Tagging
  - docker tag udagram-api-feed emb1605272/udagram-api-feed:v3
  - docker tag udagram-api-user emb1605272/udagram-api-user:v3
  - docker tag udagram-frontend emb1605272/udagram-frontend:v3
  - docker tag udagram-reverseproxy emb1605272/udagram-reverseproxy:v3
  
after_success:
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push emb1605272/udagram-api-feed:v3
  - docker push emb1605272/udagram-api-user:v3
  - docker push emb1605272/udagram-frontend:v3
  - docker push emb1605272/udagram-reverseproxy:v3