language: node_js

node_js: 
  - 13

services:
  - docker

script:
  
  # Build
  - echo '_____________beginning build'
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy  

  # Tagging
  - echo '_____________beginning tag'
  - docker tag udagram-api-feed emb1605272/udagram-api-feed:v5
  - docker tag udagram-api-user emb1605272/udagram-api-user:v5
  - docker tag udagram-frontend emb1605272/udagram-frontend:v5
  - docker tag reverseproxy emb1605272/reverseproxy:v5

  - echo 'DOCKER IMAGE LS____'
  - docker image ls
after_success:
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  # Login Docker  
  - echo '________LOGIN_______'
  #- docker login -u=emb1605272 -p=EP3E2Mr&&
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - echo 'username, password'  $DOCKER_USERNAME $DOCKER_PASSWORD
  # Pushing 
  - echo '_____________beginning push image'
  - docker push emb1605272/udagram-api-feed:v5
  - docker push emb1605272/udagram-api-user:v5
  - docker push emb1605272/udagram-frontend:v5
  - docker push emb1605272/reverseproxy:v5