language: node_js
node_js: 13
services:
  - docker

script:
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy  

  # Tagging
  - docker tag udagram-api-feed empl1/udagram-api-feed:v1
  - docker tag udagram-api-user empl1/udagram-api-user:v1
  - docker tag udagram-frontend empl1/udagram-frontend:local
  - docker tag udagram-reverseproxy empl1/udagram-reverseproxy:v1
  
after_success:
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push empl1/udagram-api-feed:v1
  - docker push empl1/udagram-api-user:v1
  - docker push empl1/udagram-frontend:local
  - docker push empl1/udagram-reverseproxy:v1

