language: node_js

node_js: 
  - 13

services:
  - docker

script:
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy  

  # Tagging
  - docker tag udagram-api-feed emb1605272/udagram-api-feed:v4
  - docker tag udagram-api-user emb1605272/udagram-api-user:v4
  - docker tag udagram-frontend emb1605272/udagram-frontend:v4
  - docker tag reverseproxy emb1605272/reverseproxy:v4
  
after_success:
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push emb1605272/udagram-api-feed:v4
  - docker push emb1605272/udagram-api-user:v4
  - docker push emb1605272/udagram-frontend:v4
  - docker push emb1605272/reverseproxy:v4