language: node_js

node_js: 
  - 13

services:
  - docker

script:
  
  # Build
  - echo '_____________beginning build'
  - docker build -t udagram-api-feed:v5 ./udagram-api-feed
  - docker build -t udagram-api-user:v5 ./udagram-api-user
  - docker build -t udagram-frontend:v5 ./udagram-frontend
  - docker build -t reverseproxy:v5 ./udagram-reverseproxy  

  # Tagging
  - echo '_____________beginning tag'
  - docker tag udagram-api-feed:v5 emb1605272/udagram-api-feed:v5
  - docker tag udagram-api-user:v5 emb1605272/udagram-api-user:v5
  - docker tag udagram-frontend:v5 emb1605272/udagram-frontend:v5
  - docker tag reverseproxy:v5 emb1605272/reverseproxy:v5

  - echo 'DOCKER IMAGE LS____'
  - docker image ls
after_success:
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  # Login Docker  
  - echo '________LOGIN_______'
  #- docker login -u=emb1605272 -p=EP3E2Mr&&
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Pushing 
  - echo '_____________beginning push image'
  - docker push emb1605272/udagram-api-feed:v5
  - docker push emb1605272/udagram-api-user:v5
  - docker push emb1605272/udagram-frontend:v5
  - docker push emb1605272/reverseproxy:v5