version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy:v7
  api-user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user:v7
  api-feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed:v7
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:v10